	AREA RESET, DATA, READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x40001000
	DCD Reset_Handler
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0,=NUM1
	LDR R1,=NUM2
	LDR R4,=RES
	
	LDR R2,[R0]
	LDR R3,[R1]
	SUB R2,R3
	STR R2,[R4]
	
STOP B STOP 	
	
NUM1 DCD 0x00000000
NUM2 DCD 0xFFFFFFFF
	AREA mydata, DATA, READWRITE
RES DCD 0x0
	END