	AREA RESET, DATA, READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x40001000
	DCD Reset_Handler
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	MOV R0,#10
	LDR R2,=Res
	MLA R1,R0,R0,R0
	LSR R1,#1
	STR R1,[R2]
	
STOP B STOP

	AREA mydata, DATA, READWRITE
Res DCD 0x0
	END